# Generated by Django 4.2.27 on 2025-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accessory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpAttach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=100, verbose_name="员工ID")),
                (
                    "attach_type",
                    models.CharField(max_length=50, verbose_name="附件类型"),
                ),
                (
                    "file",
                    models.FileField(upload_to="emp_attach/", verbose_name="附件文件"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "员工附件",
                "verbose_name_plural": "员工附件",
                "db_table": "emp_attach",
            },
        ),
    ]
