# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicOrgAttachType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("name", models.CharField(max_length=128, verbose_name="附件类型名称")),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="附件类型编码")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="描述")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "机构附件类型",
                "verbose_name_plural": "机构附件类型",
                "db_table": "medic_org_attach_type",
            },
        ),
        migrations.CreateModel(
            name="MedicOrgInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("org_name", models.CharField(max_length=255, verbose_name="机构名称")),
                ("org_code6", models.CharField(max_length=64, verbose_name="机构代码")),
                ("city_id", models.CharField(blank=True, default="", max_length=64, verbose_name="城市ID")),
                ("county_id", models.CharField(blank=True, default="", max_length=64, verbose_name="区县ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "已提交"),
                            ("APPROVED", "通过"),
                            ("REJECTED", "退回"),
                        ],
                        default="DRAFT",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="media.medicorginfo",
                        verbose_name="父节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "机构信息",
                "verbose_name_plural": "机构信息",
                "db_table": "medic_org_info",
            },
        ),
        migrations.CreateModel(
            name="MedicEmpAttachType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("name", models.CharField(max_length=128, verbose_name="附件类型名称")),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="附件类型编码")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="描述")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "员工附件类型",
                "verbose_name_plural": "员工附件类型",
                "db_table": "medic_emp_attach_type",
            },
        ),
        migrations.CreateModel(
            name="MedicEmpInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "emp_type",
                    models.CharField(
                        choices=[("BLIND", "盲人"), ("HEALTHY", "健全"), ("OTHER", "其他")],
                        max_length=32,
                        verbose_name="员工类型",
                    ),
                ),
                ("emp_name", models.CharField(max_length=255, verbose_name="员工姓名")),
                ("id_number", models.CharField(max_length=64, verbose_name="证件号")),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="联系电话")),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="media.medicorginfo",
                        verbose_name="机构",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工信息",
                "verbose_name_plural": "员工信息",
                "db_table": "medic_emp_info",
            },
        ),
        migrations.CreateModel(
            name="MedicOrgAttach",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_path", models.CharField(max_length=255, verbose_name="文件路径")),
                ("file_size", models.BigIntegerField(default=0, verbose_name="文件大小")),
                (
                    "attach_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="media.medicorgattachtype",
                        verbose_name="附件类型",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="media.medicorginfo",
                        verbose_name="机构",
                    ),
                ),
            ],
            options={
                "verbose_name": "机构附件",
                "verbose_name_plural": "机构附件",
                "db_table": "medic_org_attach",
            },
        ),
        migrations.CreateModel(
            name="MedicEmpAttach",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_path", models.CharField(max_length=255, verbose_name="文件路径")),
                ("file_size", models.BigIntegerField(default=0, verbose_name="文件大小")),
                (
                    "attach_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="media.medicempattachtype",
                        verbose_name="附件类型",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="media.medicempinfo",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工附件",
                "verbose_name_plural": "员工附件",
                "db_table": "medic_emp_attach",
            },
        ),
        migrations.CreateModel(
            name="MedicApplyApprove",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("payload", models.JSONField(default=dict, verbose_name="数据快照")),
                ("status", models.CharField(default="DRAFT", max_length=32, verbose_name="状态")),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.medicempinfo",
                        verbose_name="员工",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.medicorginfo",
                        verbose_name="机构",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
                "db_table": "medic_apply_approve",
            },
        ),
        migrations.CreateModel(
            name="MedicApplyAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("payload", models.JSONField(default=dict, verbose_name="数据快照")),
                ("status", models.CharField(default="DRAFT", max_length=32, verbose_name="状态")),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.medicempinfo",
                        verbose_name="员工",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.medicorginfo",
                        verbose_name="机构",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核记录",
                "verbose_name_plural": "审核记录",
                "db_table": "medic_apply_audit",
            },
        ),
        migrations.CreateModel(
            name="MedicApplyReject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("payload", models.JSONField(default=dict, verbose_name="数据快照")),
                ("status", models.CharField(default="DRAFT", max_length=32, verbose_name="状态")),
                ("reason", models.CharField(blank=True, default="", max_length=255, verbose_name="退回原因")),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.medicempinfo",
                        verbose_name="员工",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.medicorginfo",
                        verbose_name="机构",
                    ),
                ),
            ],
            options={
                "verbose_name": "退回记录",
                "verbose_name_plural": "退回记录",
                "db_table": "medic_apply_reject",
            },
        ),
    ]
